name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup stable toolchain with cache
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          cache: true
          components: clippy
          bins: cargo-audit,cargo-deny,cargo-geiger

      - name: Setup nightly toolchain with cache
        uses: moonrepo/setup-rust@v1
        with:
          channel: nightly
          cache: true
          bins: cargo-udeps,cargo-tarpaulin

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -W clippy::all

      - name: Run tests
        run: cargo test --all-targets --features fast-tick

      - name: Run cargo audit
        run: cargo audit

      - name: Run cargo deny
        run: cargo deny check

      - name: Run cargo geiger
        run: cargo geiger --warning

      - name: Run cargo udeps
        run: cargo +nightly udeps --all-targets

      - name: Run tarpaulin
        run: cargo +nightly tarpaulin --all-targets --features fast-tick
